# Generated by Django 6.0.5 on 2026-05-17 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgs/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='orgs/banners/', verbose_name='Banner')),
                ('basic_info', models.TextField(blank=True, verbose_name='Basic Information')),
                ('contact_information', models.TextField(blank=True, verbose_name='Contact Information')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='NotificationQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WEBPUSH', 'WebPush')], max_length=10, verbose_name='Channel')),
                ('daily_limit', models.PositiveIntegerField(default=50, verbose_name='Daily Limit')),
                ('weekly_limit', models.PositiveIntegerField(default=300, verbose_name='Weekly Limit')),
                ('monthly_limit', models.PositiveIntegerField(default=1000, verbose_name='Monthly Limit')),
                ('current_daily_usage', models.PositiveIntegerField(default=0, verbose_name='Current Daily Usage')),
                ('current_weekly_usage', models.PositiveIntegerField(default=0, verbose_name='Current Weekly Usage')),
                ('current_monthly_usage', models.PositiveIntegerField(default=0, verbose_name='Current Monthly Usage')),
                ('last_reset_daily', models.DateTimeField(auto_now_add=True, verbose_name='Last Daily Reset')),
                ('last_reset_weekly', models.DateTimeField(auto_now_add=True, verbose_name='Last Weekly Reset')),
                ('last_reset_monthly', models.DateTimeField(auto_now_add=True, verbose_name='Last Monthly Reset')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Notification Quota',
                'verbose_name_plural': 'Notification Quotas',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WEBPUSH', 'WebPush')], max_length=10, verbose_name='Channel')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='donors.donor')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager')], default='MANAGER', max_length=10, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
            },
        ),
    ]
