# Generated by Django 6.0.5 on 2026-05-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
