# Generated by Django 6.0.5 on 2026-05-17 00:28

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDonorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, verbose_name='Guest Name')),
                ('guest_notes', models.TextField(blank=True, verbose_name='Guest Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Donor Data',
                'verbose_name_plural': 'Organization Donor Data',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='Last Blood Donation Date')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, verbose_name='Allergies')),
                ('health_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, verbose_name='Known Health Conditions')),
                ('is_available_to_donate', models.BooleanField(default=False, verbose_name='Available to Donate')),
                ('resume_donation_date', models.DateField(blank=True, null=True, verbose_name='Date to Resume Donation')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='Phone Number')),
                ('invite_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Invite Token')),
                ('invite_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('REGISTERED', 'Registered'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20, verbose_name='Invite Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_locations', models.ManyToManyField(blank=True, related_name='donors', to='locations.location', verbose_name='Preferred Blood Donation Locations')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
            },
        ),
    ]
