# Generated by Django 6.0.5 on 2026-05-12 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='donor',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='donors', to='locations.location', verbose_name='Preferred Blood Donation Locations'),
        ),
    ]
