# Generated by Django 6.0.5 on 2026-05-17 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdonordata',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_data', to='donors.donor'),
        ),
        migrations.AddField(
            model_name='organizationdonordata',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_data', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='donor',
            name='organizations',
            field=models.ManyToManyField(related_name='donors', through='donors.OrganizationDonorData', to='organizations.organization', verbose_name='Organizations'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdonordata',
            unique_together={('organization', 'donor')},
        ),
    ]
