# Generated by Django 6.0.5 on 2026-05-17 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048, unique=True, verbose_name='Original URL')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Short Code')),
                ('category', models.CharField(choices=[('OTP', 'OTP Verification'), ('DONATION_ACCEPT', 'Donation Accept Link'), ('DONATION_DECLINE', 'Donation Decline Link'), ('DONATION_CONFIRM', 'Donation Confirm Link'), ('INVITE', 'Donor Invitation'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_length', models.PositiveIntegerField(editable=False, verbose_name='Message Length')),
                ('original_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Original Length (pre-truncation)')),
                ('category', models.CharField(choices=[('OTP', 'OTP Verification'), ('EMERGENCY', 'Emergency Blood Request'), ('INVITE', 'Donor Invitation'), ('OTHER', 'Other')], db_index=True, max_length=10, verbose_name='Category')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Provider Response')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('TRUNCATED', 'Truncated')], db_index=True, max_length=10, verbose_name='Status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('related_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='organizations.organization')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
