# Generated by Django 6.0.5 on 2026-05-20 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
        ('notifications', '0001_initial'),
        ('organizations', '0003_delete_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WEBPUSH', 'WebPush')], max_length=10, verbose_name='Channel')),
                ('category', models.CharField(choices=[('OTP', 'OTP Verification'), ('EMERGENCY', 'Emergency Blood Request'), ('INVITE', 'Donor Invitation'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=10, verbose_name='Category')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('TRUNCATED', 'Truncated')], default='SENT', max_length=50, verbose_name='Status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure Reason')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='donors.donor')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
