# Generated by Django 6.0.5 on 2026-05-12 03:06

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('post_code', models.CharField(max_length=10, verbose_name='Post Code')),
                ('area_name', models.CharField(max_length=100, verbose_name='Area Name')),
                ('station', models.CharField(max_length=100, verbose_name='Station/Upazila')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('division', models.CharField(max_length=100, verbose_name='Division')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['division', 'district', 'station', 'area_name'],
                'indexes': [models.Index(fields=['post_code'], name='locations_l_post_co_df56f8_idx'), models.Index(fields=['area_name'], name='locations_l_area_na_746938_idx'), models.Index(fields=['station'], name='locations_l_station_bcae9d_idx'), models.Index(fields=['district'], name='locations_l_distric_8c2a5d_idx')],
            },
        ),
    ]
