# Generated by Django 6.0.5 on 2026-05-06 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (e.g., +8801712345678 or 01712345678).', regex='^(?:\\+88|88)?(01[3-9]\\d{8})$')])),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP Request',
                'verbose_name_plural': 'OTP Requests',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (e.g., +8801712345678 or 01712345678).', regex='^(?:\\+88|88)?(01[3-9]\\d{8})$')], verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='NIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='nids/front/')),
                ('back_image', models.ImageField(upload_to='nids/back/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nid_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NID Verification',
                'verbose_name_plural': 'NID Verifications',
            },
        ),
    ]
