# Generated by Django 6.0.5 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprequest_user_is_phone_verified_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Verification Attempts'),
        ),
    ]
