# Generated by Django 6.0.5 on 2026-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verification_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='health_conditions',
            field=models.TextField(blank=True, verbose_name='Known Health Conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available_to_donate',
            field=models.BooleanField(default=False, verbose_name='Available to Donate'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Blood Donation Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date to Resume Donation'),
        ),
    ]
