# Generated by Django 6.0.5 on 2026-05-06 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_allergies_user_blood_group_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE users_user ALTER COLUMN allergies TYPE varchar(100)[] USING CASE WHEN allergies = '' THEN '{}' ELSE string_to_array(allergies, ',') END;",
            reverse_sql="ALTER TABLE users_user ALTER COLUMN allergies TYPE text USING array_to_string(allergies, ',');"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE users_user ALTER COLUMN health_conditions TYPE varchar(100)[] USING CASE WHEN health_conditions = '' THEN '{}' ELSE string_to_array(health_conditions, ',') END;",
            reverse_sql="ALTER TABLE users_user ALTER COLUMN health_conditions TYPE text USING array_to_string(health_conditions, ',');"
        ),
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Known Health Conditions'),
        ),
    ]
