# Generated by Django 6.0.5 on 2026-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0005_alter_user_allergies_alter_user_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='interested_donors', to='locations.location', verbose_name='Preferred Blood Donation Locations'),
        ),
    ]
