# Generated by Django 6.0.5 on 2026-05-10 20:49

import project_rokto.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_preferred_locations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', project_rokto.users.models.CustomUserManager()),
            ],
        ),
    ]
