# Generated by Django 6.0.5 on 2026-05-06 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason for Request')),
                ('bags_needed', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Bags Needed')),
                ('donation_date', models.DateField(verbose_name='Proposed Donation Date')),
                ('hospital', models.CharField(max_length=255, verbose_name='Hospital/Location Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Seeker')),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequestDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10, verbose_name='Response Status')),
                ('seeker_confirmation', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No')], default='PENDING', max_length=10, verbose_name='Seeker Confirmation')),
                ('donor_confirmation', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No')], default='PENDING', max_length=10, verbose_name='Donor Confirmation')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Secure Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='blood_requests.bloodrequest', verbose_name='Blood Request')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Donor')),
            ],
            options={
                'verbose_name': 'Blood Request Donor',
                'verbose_name_plural': 'Blood Request Donors',
                'unique_together': {('blood_request', 'donor')},
            },
        ),
    ]
