# Generated by Django 6.0.5 on 2026-05-17 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='Reason for Request')),
                ('bags_needed', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Bags Needed')),
                ('donation_date', models.DateField(verbose_name='Proposed Donation Date')),
                ('hospital', models.CharField(max_length=255, verbose_name='Hospital/Location Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequestDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10, verbose_name='Response Status')),
                ('seeker_confirmation', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No')], default='PENDING', max_length=10, verbose_name='Seeker Confirmation')),
                ('donor_confirmation', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No')], default='PENDING', max_length=10, verbose_name='Donor Confirmation')),
                ('seeker_confirmation_at', models.DateTimeField(blank=True, null=True, verbose_name='Seeker Confirmation At')),
                ('donor_confirmation_at', models.DateTimeField(blank=True, null=True, verbose_name='Donor Confirmation At')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Secure Token')),
                ('donor_contact_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Donor Contact Accessed At')),
                ('seeker_contact_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Seeker Contact Accessed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Blood Request Donor',
                'verbose_name_plural': 'Blood Request Donors',
            },
        ),
    ]
