# Generated by Django 6.0.5 on 2026-05-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='donor_contact_accessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Donor Contact Accessed At'),
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='seeker_contact_accessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seeker Contact Accessed At'),
        ),
    ]
