# Generated by Django 6.0.5 on 2026-05-12 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Seeker'),
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='blood_requests.bloodrequest', verbose_name='Blood Request'),
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Donor'),
        ),
        migrations.AlterUniqueTogether(
            name='bloodrequestdonor',
            unique_together={('blood_request', 'donor')},
        ),
    ]
