# Generated by Django 6.0.5 on 2026-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_bloodrequestdonor_donor_contact_accessed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='donor_confirmation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Donor Confirmation At'),
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='seeker_confirmation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seeker Confirmation At'),
        ),
    ]
