# Generated by Django 6.0.5 on 2026-05-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='bloodrequestdonor',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Responded At'),
        ),
    ]
