#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py wait_for_db
python manage.py migrate django_celery_beat
rm -f './celerybeat.pid'
celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
